apiVersion: v1
data:
  nginx-1.conf: |
    server {
        listen       8081;
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  name: nginx-1-conf

---

apiVersion: v1
data:
  nginx-2.conf: |
    server {
        listen       8082;
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  name: nginx-2-conf

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: web-1
spec:
  containers:
  - image: nginx
    name: nginx-1
    ports:
    - containerPort:  8081
      protocol: TCP
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
      readOnly: true
    lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  apt-get update;
                  apt-get -y install curl
  volumes:
  - name: config
    configMap:
      name: nginx-1-conf
      items:
      - key: nginx-1.conf
        path: default.conf



---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: web-2
spec:
  containers:
  - image: nginx
    name: nginx-2
    ports:
    - containerPort:  8082
      protocol: TCP
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
      readOnly: true
    lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  apt-get update;
                  apt-get -y install curl
  volumes:
  - name: config
    configMap:
      name: nginx-2-conf
      items:
      - key: nginx-2.conf
        path: default.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-web
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: web-1

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2-web
spec:
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: web-2
